### PR TITLE
Updated Docker compose, tested locally and remotely

### PR DESCRIPTION
**Pull request by br2490**
@McFateM I need confirmation the command works on a Mac to bring up ISLE.localdomain, when you have a chance.

--
This updates the compose.

Adds instructions that are quick, and work. there will be issue with the uid/gid 10,000 owning things, but that was a patch of need!

Additionally removes nginx-debug command! We will not be needing that.

Please merge.

### CODE REVIEW

**Comment by McFateM** [comment]
Working on it now, and migrating to a new iMac at the same time.  Slow going because of it.

I confirmed that I can hit Traefik at http://isle.localdomain:8080/dashboard/#/ and it reports the image below:

[cid:CDF58964-8C63-4BF3-A4F8-EA5BD1B2F004]

However, I can’t open Portainer at any address.  Based on info above, any clue what might be missing/wrong?

-Mark M.

**Comment by br2490** [comment]
@g7morris I have updated the docker-compose.yml, please let me know.

**Comment by McFateM** [comment]
@br2490 Working on it now, and migrating to a new iMac at the same time.  Slow going because of it.  I can’t open Portainer at any address.  Any clue what might be missing/wrong?

**Comment by br2490** [comment]
@g7morris thank you for taking time to review this and approve - I'm aware this is crunch time.  I am glad this works and sorry for taking time away.

**Pull request merged**
